name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: docker
    container:
      image: redemonbr/android-sdk:node-next
      variables:
        ASDK_ACCEPT_LICENSES: "yes"
        ASDK_ACCEPT_LICENSES_SILENT: "yes"
    steps:
      - name: Clone repo
        uses: https://github.com/actions/checkout@v4
      - name: Setup Gradle
        uses: https://github.com/gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate

  build:
    name: Build app
    needs: check_wrapper
    runs-on: docker
    container:
      image: redemonbr/android-sdk:node-next
      variables:
        ASDK_ACCEPT_LICENSES: "yes"
        ASDK_ACCEPT_LICENSES_SILENT: "yes"
    steps:
      - name: Clone repo
        uses: https://github.com/actions/checkout@v4
      - name: Set up JDK
        uses: https://github.com/actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build app
        run: gradle assembleDevDebug
      - name: Upload APK
        uses: https://github.com/actions/upload-artifact@v4
        with:
          name: fabsemanga-${{ github.sha }}.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
