name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: docker
    container:
      image: docker.io/redemonbr/android-sdk:node-alpine-next
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: https://github.com/gradle/wrapper-validation-action@v1

  build:
    name: Build app
    needs: check_wrapper
    runs-on: docker
    container:
      image: docker.io/redemonbr/android-sdk:node-alpine-next
    steps:
      - name: Clone repo
        uses: https://github.com/actions/checkout@v4
      - name: Set up JDK
        uses: https://github.com/actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build app
        uses: https://github.com/gradle/gradle-command-action@v2
        with:
          arguments: assembleDevDebug
      - name: Upload APK
        uses: https://github.com/actions/upload-artifact@v3
        with:
          name: Fabsemanga-${{ github.sha }}.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
