name: Issue moderator

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  moderate:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:full-latest
    steps:
      - name: Moderate issues
        uses: https://github.com/tachiyomiorg/issue-moderator-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-label: Duplicate
          auto-close-rules: |
            [
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed."
              },
              {
                "type": "body",
                "regex": ".*\\* (Fabsemanga version|Android version|Device): \\?.*",
                "message": "Requested information in the template was not filled out."
              },
              {
                "type": "both",
                "regex": "^(?!.*myanimelist.*).*(aniyomi|anime).*$",
                "ignoreCase": true,
                "message": "Fabsemanga does not support anime and has no plans to support anime. In addition Fabsemanga is not affiliated with Aniyomi https://github.com/jmir1/aniyomi"
              },
              {
                "type": "both",
                "regex": ".*(?:fail(?:ed|ure|s)?|can\\s*(?:no|')?t|(?:not|un).*able|(?<!n[o']?t )blocked by|error) (?:to )?(?:get past|by ?pass|penetrate)?.*cloud ?fl?are.*",
                "ignoreCase": true,
                "labels": ["Cloudflare protected"],
                "message": "Extensions are no longer maintained by Mihon nor its forks, pls forward your issues to the maintainer of the extension repo you use. If it doesn't work, migrate to other sources or wait until they lower their protection."
              }
            ]
          auto-close-ignore-label: do-not-autoclose
