name: Update dependencies

on:
  schedule:
    - cron: '00 6 1 * *'

jobs:
  update-dependencies:
    runs-on: docker
    container:
      image: redemonbr/android-sdk:node-next
      variables:
        ASDK_ACCEPT_LICENSES: "yes"
        ASDK_ACCEPT_LICENSES_SILENT: "yes"
    steps:
      - uses: https://github.com/actions/checkout@v4
      - name: Set up JDK
        uses: https://github.com/actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Setup Gradle
        uses: https://github.com/gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: Perform dependencies resolution and update
        run: gradle versionCatalogUpdate
      - name: Create Pull Request
        uses: https://github.com/peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update dependencies
          committer: update_dependencies@fabseman.space
          author: fabsedep@codeberg.com
          title: Update dependencies
          body: |
            Dependencies update.
            Check the Version Catalog to see which dependencies need an update.
      branch: update-dependencies
      delete-branch: true