when:
  event: tag

steps:
  build:
    image: thyrlian/android-sdk
    commands:
      - echo -e "storePassword=$${KEYSTOREPASS}\nkeyPassword=$${KEYPASS}\nkeyAlias=$${ALIAS}\nstoreFile=release-key.jks" | base64 -d > keystore.properties
      - echo "$${SIGNING_KEY}" | base64 -d > app/release-key.jks
      - ./gradlew assembleStandardRelease
  release:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      file_exists: overwrite
      files:
        - app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk
        - app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk
        - app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk
      api_key:
        from_secret: FABSEGIT_RELEASE
      target: master
