when:
  event: tag

steps:
  build:
    image: thyrlian/android-sdk
    commands:
      - echo "$${SIGNING_KEY}" | base64 -d > app/keystore.p12
      - ./gradlew assembleStandardRelease -release_store_file="keystore.p12" -Drelease_store_password="$${KEYSTOREPASS}" -Drelease_key_alias="$${ALIAS}" -Drelease_key_password="$${KEYPASS}"
  release:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      file_exists: overwrite
      files:
        - app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk
        - app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk
        - app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk
      api_key:
        from_secret: FABSEGIT_RELEASE
      target: master
